FROM debian:bookworm-slim
ENV DEBIAN_FRONTEND=noninteractive
RUN set -ex \
	&& apt-get update \
	&& apt-get dist-upgrade -y \
	&& apt-get install -y \
		build-essential \
		cmake \
		curl \
		gcc-arm-none-eabi \
		git \
		gnupg \
		libnewlib-arm-none-eabi \
		libstdc++-arm-none-eabi-newlib \
		opensc \
		pcsc-tools \
		python3 \
		xz-utils \
	&& apt-get clean \
	&& rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*


